# Generated by Django 3.0.5 on 2020-04-13 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0002_auto_20200413_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='precio_igv',
            new_name='precio_sin_igv',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='precio_total',
        ),
        migrations.AddField(
            model_name='ventas',
            name='monto_igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='creado_por',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
