# Generated by Django 3.0.5 on 2020-04-13 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='creado_por',
            field=models.ForeignKey(max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='libros',
            name='fecha_creacion',
            field=models.DateTimeField(default='2020-02-02', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libros',
            name='fecha_modificacion',
            field=models.DateTimeField(default='2020-02-02', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libros',
            name='resumen',
            field=models.CharField(default='2020-02-02', max_length=3000),
            preserve_default=False,
        ),
    ]
