# Generated by Django 3.0.5 on 2020-04-13 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0003_auto_20200413_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='stock',
            field=models.PositiveIntegerField(default=22, verbose_name='Cantidad disponible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libros',
            name='creado_por',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
