# Generated by Django 3.0.5 on 2020-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_auto_20200413_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='precio_dolar',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='Precio Dólar'),
            preserve_default=False,
        ),
    ]
