# Generated by Django 3.0.5 on 2020-04-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200413_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha_creacion',
            field=models.DateTimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_modificacion',
            field=models.DateTimeField(max_length=20),
        ),
    ]
