# Generated by Django 3.0.5 on 2020-04-13 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_auto_20200413_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dni',
            field=models.CharField(default='12345678', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='red_social',
            field=models.CharField(default='fb.com/3', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='creado_por',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
